builds:
  - binary: godirtreegen
    goos:
      - darwin
      - linux
      - freebsd 
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: godirtreegen
    homepage: "https://github.com/rexsimiloluwah/godirtreegen"
    tap:
      owner: rexsimiloluwah
      name: godirtreegen
    commit_author:
      name: rexsimiloluwah
      email: rexsimiloluwa@gmail.com

checksum:
  name_template: 'checksums.txt'